import { Category } from './category';
export interface Item{
    Item_id: number;
    Item_No: string;
    ItemCat: Category[];
    Arb_Des: string;
    Eng_Des: string;
    Unit1: number;
    UntPri1: number;   
    Pack1: number;  
    OpenQty: number;
    // StartCost: number;
    // LastCost: number;
    // Price1: number;
    // Price2: number;
    // Price4: number;
    // Price5: number;
    // Price6: number;
    // Unit2: number;
    // UntPri2: number;
    // Pack2: number;
    // Unit3: number;
    // UntPri3: number;
    // Pack3: number;
    // Unit4: number;
    // UntPri4: number;
    // Pack4: number;
    // Unit5: number;
    // UntPri5: number;
    // Pack5: number;
    // DefultUnit: number;
    // DefultVendor: number;
    // QtyLvl: number;
    // ItmLoc: string;
    // BarCod1: string;
    // BarCod2: string;
    // BarCod3: string;
    // BarCod4: string; 
    // BarCod5: string; 
    // Lot: number;
    // QtyMax: number;
    // LrnExp: number;
    // DMY: number; 
    // ItmTyp: number; 
    // DefPack: number;
    // ItmImg: number;
    // Group_Code: string;
    // Item_No_Only: string; 
    // Shipping_Cost: number; 
    // Sn: string;
    // SeaCost: number;
    // Note: string;
    // St: number; 
    // ItmNature: number; 
    // Tax: number;
    // ItmPOS: number;
}